Add request controller
BlackWolfBY/dreamcar_api pull request #1
Opened 2021-01-17 00:51 UTC by OlyaHudoleeva

2021-01-17 09:50 UTC, BlackWolfBY requested changes

2021-01-17 09:50 UTC, BlackWolfBY commented on src/app.module.ts
> +  imports: [RequestsModule],
На данный момент у нас в системе предполагается только один модуль. Нужно убрать RequestsModule, а все его зависимости перенести в AppModule

2021-01-17 09:50 UTC, BlackWolfBY commented on src/controller/request.controller.ts
> +    draft(@Param('id') id: string) {
Метод вне зоны видимости т.к. совпадает путь в декораторе @Put(':id')

2021-01-17 09:50 UTC, BlackWolfBY commented on src/controller/request.controller.ts
> +    @Put(':id')
Аналогично коменту выше. Лучше напиши @Patch(":id/close")

2021-01-17 09:50 UTC, BlackWolfBY commented on src/model/attribute/request.status.ts
> +export enum RequestStatus {
Этот файл должен лежать в src/constants/index.ts

Если я не ошибаюсь, то у offers аналогичные статусы. Неплохо бы было переиспользовать данное перечисление. Есть предложение переименовать в StockStatus

2021-01-17 09:50 UTC, BlackWolfBY commented on src/model/attribute/request.status.ts
> +    Opened,
Окончания излишни. Путь будет OPEN, DRAFT и CLOSE. Значения перечисления пишутся в аперкейсе

2021-01-17 09:50 UTC, BlackWolfBY commented on src/model/dto/request.dto.ts
> +import { RequestStatus } from "../attribute/request.status"
Это должно лежать в /src/dto/request.dto.ts

2021-01-17 09:50 UTC, BlackWolfBY commented on src/model/dto/request.dto.ts
> +export class RequestDto {
Переименуй класс в StockRequestDto. Я создал entity StockRequest т.к. Request нативный интерфейс в typescript и были проблемы с импортами

2021-01-17 09:50 UTC, BlackWolfBY commented on src/model/request.module.ts
> +import { Module } from "@nestjs/common";
Этого файла не должно быть

2021-01-17 09:50 UTC, BlackWolfBY commented on src/model/schemas/request.schema.ts
> +import { RequestStatus } from "../attribute/request.status"
Этого файла не должно быть

2021-01-17 09:50 UTC, BlackWolfBY commented on src/service/request.service.ts
> +export class RequestsService {
Переименуй в StockRequestService

2021-01-17 09:50 UTC, BlackWolfBY commented on src/service/request.service.ts
> +    getAll() {
Во всех методах сервиса должно быть чёткое указание что возвращается

2021-01-17 09:50 UTC, BlackWolfBY commented on src/controller/request.controller.ts
> +export class RequestsController {
Переименуй в StockRequestController

2021-01-17 09:50 UTC, BlackWolfBY commented on src/controller/request.controller.ts
> +    getAll() {
Все методы контроллера должны возвращать тип

2021-01-18 13:28 UTC, OlyaHudoleeva commented on src/app.module.ts
> +  imports: [RequestsModule],
Сделано

2021-01-18 13:31 UTC, OlyaHudoleeva commented on src/controller/request.controller.ts
> +    draft(@Param('id') id: string) {
Сделано

2021-01-18 13:31 UTC, OlyaHudoleeva commented on src/controller/request.controller.ts
> +    @Put(':id')
Сделано

2021-01-18 13:43 UTC, OlyaHudoleeva commented on src/model/attribute/request.status.ts
> +    Opened,
Сделано

2021-01-18 13:43 UTC, OlyaHudoleeva commented on src/model/schemas/request.schema.ts
> +import { RequestStatus } from "../attribute/request.status"
Сделано

2021-01-18 14:08 UTC, OlyaHudoleeva commented on src/service/request.service.ts
> +export class RequestsService {
Сделано

2021-01-18 14:09 UTC, OlyaHudoleeva commented on src/model/attribute/request.status.ts
> +export enum RequestStatus {
сделан отдельный енам

2021-01-18 14:18 UTC, OlyaHudoleeva commented on src/service/request.service.ts
> +    getAll() {
Сделано

2021-01-18 14:18 UTC, OlyaHudoleeva commented on src/controller/request.controller.ts
> +export class RequestsController {
Сделано

2021-01-18 14:18 UTC, OlyaHudoleeva commented on src/controller/request.controller.ts
> +    getAll() {
Сделано

2021-01-18 14:38 UTC, merged